### PR TITLE
fix(version): remove `workspace:` prefix on external deps, fixes #200

### LINKED ISSUE #200: PNPM workspace: protocol is not removed before publish
### Describe the bug

As titled. This broke currently our release process :scream: 

```
lerna publish --conventional-commits --create-release github --allow-branch main --yes --message="chore(release): Publish [skip ci]"
```

### Reproduction

1. Create PNPM workspace
2. Use a dependency with workspace: protocol
3. Publish with lerna.
4. workspace: is still in the manifest.

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

```shell
| Executable        | Version |
| ----------------- | ------- |
| `lerna --version` | v1.4.0 |
| `npm --version`   | VERSION |
| `yarn --version`  | VERSION |
| `node --version`  | VERSION |

---
OR simply run `npx lerna info` command
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by ghiscoding**
## Description
`workspace:` prefix should be removed on every dependencies being published

## Motivation and Context
we shouldn't publish dependencies with `workspace:` even for external dependencies (not handled by Lerna-Lite), fixes #200

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: packages/core/src/package.ts [hunk 1]
```diff
@@ -330,4 +358,21 @@ export class Package {
       depCollection[depName] = hosted.toString({ noGitPlus: false, noCommittish: false });
     }
   }
+
+  private retrievePackageDependencies(depName: string): string[] {
```
Comment (StarpTech) [inline packages/core/src/package.ts:362]: @ghiscoding I think you forgot peerDependencies.

File: packages/publish/src/publish-command.ts [hunk 2]
```diff
@@ -568,18 +590,36 @@ export class PublishCommand extends Command<PublishCommandOption> {
...
+          resolved,
+          depVersion,
+          this.savePrefix,
+          this.options.workspaceStrictMatch,
+          this.commandName
+        );
+      }
+
+      // 2. remove any "workspace:" prefix from the package to be published any of external dependencies (without anything being bumped)
+      // we will only accept "workspace:" with semver version, for example "workspace:1.2.3" is ok but "workspace:*" will throw
```
Comment (StarpTech) [inline packages/publish/src/publish-command.ts:618]: You mean "will log an error" correct?

File: packages/publish/src/publish-command.ts [hunk 3]
```diff
@@ -568,18 +590,36 @@ export class PublishCommand extends Command<PublishCommandOption> {
...
+      for (const [_depName, resolved] of node.externalDependencies) {
+        if (/^(workspace:)+(.*)$/.test(resolved.workspaceTarget)) {
```
Comment (StarpTech) [inline packages/publish/src/publish-command.ts:620]: Why is it needed to check here for the protocol?
